/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import { AllBoards, allBoardsSchema } from '../models/allBoards';
import { Board, boardSchema } from '../models/board';
import { BoardRequest, boardRequestSchema } from '../models/boardRequest';
import { BaseController } from './baseController';

export class BoardsController extends BaseController {
  /**
   * Endpoint to create a new board
   *
   * @param boardRequest name of the board
   * @return Response from the API call
   */
  async createBoard(
    boardRequest: BoardRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Board>> {
    const req = this.createRequest('POST', '/boards');
    req.baseUrl('default');
    const mapped = req.prepareArgs({
      boardRequest: [boardRequest, boardRequestSchema],
    });
    req.json(mapped.boardRequest);
    req.throwOn(400, ApiError, 'The board name is invalid or duplicate.');
    return req.callAsJson(boardSchema, requestOptions);
  }

  /**
   * List all Pinterest boards
   *
   * @return Response from the API call
   */
  async getAllBoards(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AllBoards>> {
    const req = this.createRequest('GET', '/boards');
    return req.callAsJson(allBoardsSchema, requestOptions);
  }
}
