/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import { BoardRequest, boardRequestSchema } from '../models/boardRequest';
import { NewBoard, newBoardSchema } from '../models/newBoard';
import { BaseController } from './baseController';

export class BoardsController extends BaseController {
  /**
   * Endpoint to create a new board
   *
   * @param boardRequest name of the board
   * @return Response from the API call
   */
  async createBoard(
    boardRequest: BoardRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NewBoard>> {
    const req = this.createRequest('POST', '/boards');
    req.baseUrl('default');
    const mapped = req.prepareArgs({
      boardRequest: [boardRequest, boardRequestSchema],
    });
    req.json(mapped.boardRequest);
    req.throwOn(400, ApiError, 'The board name is invalid or duplicate.');
    return req.callAsJson(newBoardSchema, requestOptions);
  }
}
