/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import {
  CreatePinResponse,
  createPinResponseSchema,
} from '../models/createPinResponse';
import { NewPinRequest, newPinRequestSchema } from '../models/newPinRequest';
import { BaseController } from './baseController';

export class PinsController extends BaseController {
  /**
   * Create a new pin in Pinterest board.
   *
   * @param body
   * @return Response from the API call
   */
  async createPin(
    body: NewPinRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreatePinResponse>> {
    const req = this.createRequest('POST', '/pins');
    const mapped = req.prepareArgs({ body: [body, newPinRequestSchema] });
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Invalid pin parameters');
    req.throwOn(403, ApiError, 'The pin\'s image is too small, too large, or is broken');
    req.throwOn(404, ApiError, 'Board or section not found');
    req.throwOn(429, ApiError, 'This request exceeded a rate limit. This can happen if a client exceeds one of the published rate limits or if multiple write operations are applied to an object within a short time window.');
    return req.callAsJson(createPinResponseSchema, requestOptions);
  }
}
