/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface BoardRequest {
  name: string;
  description: string;
  privacy: string;
}

export const boardRequestSchema: Schema<BoardRequest> = object({
  name: ['name', string()],
  description: ['description', string()],
  privacy: ['privacy', string()],
});
