/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface BoardOwner {
  username: string;
}

export const boardOwnerSchema: Schema<BoardOwner> = object({
  username: ['username', string()],
});
