/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Media {
  mediaType: string;
}

export const mediaSchema: Schema<Media> = object({
  mediaType: ['media_type', string()],
});
