/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Type to define media input. */
export interface MediaSourceFile {
  /** States the type of the media input. */
  sourceType: string;
  /** This is the URL of the media. */
  url: string;
}

export const mediaSourceFileSchema: Schema<MediaSourceFile> = object({
  sourceType: ['source_type', string()],
  url: ['url', string()],
});
