/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface MediaSourceFile {
  sourceType: string;
  url: string;
}

export const mediaSourceFileSchema: Schema<MediaSourceFile> = object({
  sourceType: ['source_type', string()],
  url: ['url', string()],
});
