/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Owner, ownerSchema } from './owner';

export interface NewBoard {
  id: string;
  name: string;
  description: string;
  owner: Owner;
  privacy: string;
}

export const newBoardSchema: Schema<NewBoard> = object({
  id: ['id', string()],
  name: ['name', string()],
  description: ['description', string()],
  owner: ['owner', lazy(() => ownerSchema)],
  privacy: ['privacy', string()],
});
