/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { MediaSourceFile, mediaSourceFileSchema } from './mediaSourceFile';

export interface NewPinRequest {
  link?: string;
  title?: string;
  description?: string;
  dominantColor?: string;
  altText?: string;
  boardId: string;
  boardSectionId?: string;
  mediaSource: MediaSourceFile;
  parentPinId?: string;
}

export const newPinRequestSchema: Schema<NewPinRequest> = object({
  link: ['link', optional(string())],
  title: ['title', optional(string())],
  description: ['description', optional(string())],
  dominantColor: ['dominant_color', optional(string())],
  altText: ['alt_text', optional(string())],
  boardId: ['board_id', string()],
  boardSectionId: ['board_section_id', optional(string())],
  mediaSource: ['media_source', lazy(() => mediaSourceFileSchema)],
  parentPinId: ['parent_pin_id', optional(string())],
});
