/**
 * Pinterest APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Media, mediaSchema } from './media';
import { Owner, ownerSchema } from './owner';

/** Model to create a new pin. */
export interface NewPin {
  /** ID of the new pin. */
  id: string;
  /** Timestamp at which the pin is created. */
  createdAt: string;
  /** Link to the created pin. */
  link: string;
  /** Title of the created pin. */
  title: string;
  /** Describes what the pin is about. */
  description: string;
  /** States the dominant color of the created pin. */
  dominantColor: string;
  /** ALT text of the created pin. */
  altText: string;
  /** This is the board ID of the board in which the pin was created. */
  boardId: string;
  /** This is the board section ID of the parent board. */
  boardSectionId: string;
  /** States the owner of the board in which the pin is created. */
  boardOwner: Owner;
  /** Defines the type of media. */
  media: Media;
  /** This is the ID of parent pin. */
  parentPinId: string;
}

export const newPinSchema: Schema<NewPin> = object({
  id: ['id', string()],
  createdAt: ['created_at', string()],
  link: ['link', string()],
  title: ['title', string()],
  description: ['description', string()],
  dominantColor: ['dominant_color', string()],
  altText: ['alt_text', string()],
  boardId: ['board_id', string()],
  boardSectionId: ['board_section_id', string()],
  boardOwner: ['board_owner', lazy(() => ownerSchema)],
  media: ['media', lazy(() => mediaSchema)],
  parentPinId: ['parent_pin_id', string()],
});
