name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: Tests for ${{ matrix.node }}
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.head_commit.message), 'skip ci')"
    strategy:
      matrix:
       node: ["12.x", "14.x"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Lint
        run: yarn lint

      - name: Code formatting
        run: yarn check-style
